### ISSUE TITLE
I want to add a rom that's not in the list. How do I add it?

### ISSUE THREAD

**Issue by khirendra03** [Uotan-Dev/UotanWorkStation-ROM-Builder#2]

**Comment by mujianwu** [comment]
Sorry, this project was built using a private server, not a server provided by GitHub Action. The ROM source code is always stored in a specific directory on the private server and is pulled by the administrator. In addition, this project cannot be directly used after forking, and simply changing the running server to the server provided by GitHub Action is also not possible (without a compilation environment). Besides, the configuration of the server provided by GitHub Actions is insufficient to support the complete compilation of the ROM.
